name: Scord
main: io.github.lawye.scord.Scord
version: 1.1
api-version: 1.16
author: lawye
website: lawye.github.io
commands:
  scord:
    description: all control of this plugin
    usage: /<command> [on|off]|/<command> player [player] [score|config] [args]|/<command> board [title|numberprefix|maxmiumleaders|nameprefix] set [expression]|/<command> blacklist [add|remove|find] [player]
permissions:
  scord.*:
    description: anything
    children:
      scord.set: true
      scord.basic: true
  scord.set:
    description: Set leader's number and user's
    default: op
  scord.basic:
    description: Set show the board or not
    default: true
