name: Scord
main: io.github.lawye.scord.Scord
version: 1.0
api-version: 1.16
author: lawye
website: lawye.github.io
commands:
  scord:
    description: turn on or turn off players scoreboard display.
    usage: /<command> [on|off]
  scordset:
    description: settings for Scord
    usage: /<command> [num|data] (user) num
permissions:
  scord.*:
    description: anything
    children: :
      scord.set: true
      scord.basic: true
  scord.set:
    description: Set leader's number and user's
    default: op
  scord.basic:
    description: Set show the board or not
    default: true
